# Generated by Django 4.2.13 on 2025-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Education', 'Education'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Other', 'Other'), ('More', 'More')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
