# Generated by Django 4.2.13 on 2026-01-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0002_alter_expense_category_alter_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Education', 'Education'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Enjoyment', 'Enjoyment'), ('Other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Education', 'Education'), ('Food', 'Food'), ('Clothing', 'Clothing'), ('Rent', 'Rent'), ('Bills', 'Bills'), ('Enjoyment', 'Enjoyment'), ('Other', 'Other')], max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category', 'month', 'year')},
            },
        ),
    ]
