# Generated by Django 4.2.13 on 2026-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_category_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
    ]
